### PR TITLE
make localhost:8000/register hyperlink

### PR DESCRIPTION
**Pull request by vaibhavmule**

### CODE REVIEW

**Comment by josephmancuso** [comment]
you want this to go into the 2.1 branch or 2.0? It's currently going into 2.1 ☝️

**Comment by vaibhavmule** [comment]
I think it is relevant to both.

**Comment by josephmancuso** [comment]
yeah i think you based it off 2.1. Switching to 2.0 showed 10 or so commits to merge

**Comment by vaibhavmule** [comment]
Yes I will do that

**Pull request closed without merging**
