### PR TITLE
Add missing validation rules

### PR DESCRIPTION
**Pull request by girardinsamuel**
@josephmancuso 
* I added missing validation rules (regex, is_list and date)
* I also dropped table for validation rules as it was a nightmare to insert a rule in alphabetic order inside the table ... (I am open for ideas but for now I revert it to a bullet list)

### CODE REVIEW

**Comment by girardinsamuel** [comment]
I reordered the rules and it has polluted diff view... also I guess I have a .md formatter which  `\_` to `_`

**Review by josephmancuso — CHANGES_REQUESTED** [review]
It doesn't look like its in a table anymore?

**Comment by josephmancuso** [comment]
But you the man! I was gonna get to this later on. Maybe tonight but didn't wanna forget about it but you nailed it! HUGE thanks. You've been huge lately! love it

**Comment by girardinsamuel** [comment]
@josephmancuso 
> It doesn't look like its in a table anymore?

Well no it is not anymore because I was having hard time to insert validation rules (to order them alphabetically) because then it shifts all elements of the table. So I reverted the table to a bullet list.

I can edit it if you want but have no good formatting idea for those rules (I believe that the table, even if looking great, is not really maintainable).

**Comment by josephmancuso** [comment]
Fixed this to add it back into a table

**Pull request merged**
