### PR TITLE
fix typo and grammar

### PR DESCRIPTION
**Pull request by vaibhavmule**

### CODE REVIEW

**Comment by nioperas06** [comment]
Already added 👍

**Comment by vaibhavmule** [comment]
You mean this, https://github.com/MasoniteFramework/docs/commit/73ee6ef504a8226f55306932b759cdb11b20c884

**Comment by josephmancuso** [comment]
@nioperas06 do you have merge permissions in this repo?

**Comment by nioperas06** [comment]
From GitBook, yes.

**Comment by josephmancuso** [comment]
ok i granted you access to the repo. if you see a pull request like this make sure you merge the PR instead of editing in Gitbook since it allows people like @vaibhavmule and @mitchdennett do get those contribution points. If it's an issue you can go ahead and edit in gitbook.

**Comment by nioperas06** [comment]
Sounds good 👍

**Pull request closed without merging**
